name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'
          
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/workway .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/workway

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy workway \
            --image us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/backend/workway \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080 \
            --timeout 300s \
            --set-env-vars "NODE_ENV=production" \